# Debug Container Compose Configuration
# Compose Specification 2025 (https://github.com/compose-spec/compose-spec)

name: wolfguard-debug

services:
  wolfguard-debugger:
    container_name: wolfguard-debugger
    image: localhost/wolfguard-debugger:latest

    build:
      context: .
      dockerfile: docker/Containerfile.debug

    # Keep container running
    tty: true
    stdin_open: true

    # Mount current directory for scripts
    volumes:
      - ./scripts:/workspace/scripts:rw
      - ./reports:/workspace/reports:rw
      - ./screenshots:/workspace/screenshots:rw
      - ../src:/workspace/site-src:ro  # Read-only access to source

    # Connect to same network as Traefik (if needed for internal testing)
    networks:
      - debug-network

    # Environment variables
    environment:
      - TZ=UTC
      - TARGET_URL=https://wolfguard.io
      - INTERNAL_URL=http://wolfguard-site:8080

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 512M

    # Security options (less restrictive than production for debugging)
    security_opt:
      - no-new-privileges:true

    # Metadata labels
    labels:
      - "com.wolfguard.project=wolfguard-debug"
      - "com.wolfguard.description=Frontend debugging tools"
      - "com.wolfguard.environment=development"

networks:
  debug-network:
    driver: bridge
    labels:
      - "com.wolfguard.project=wolfguard-debug"
