name: Feature Request
description: Suggest a new feature or enhancement for the WolfGuard website
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternative solutions or features you've considered
      placeholder: Alternatively, we could...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature affect?
      options:
        - UI/UX
        - Performance
        - Accessibility
        - SEO
        - Security
        - Documentation
        - DevOps/Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Significantly impacts usability
        - Critical - Blocking current use
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: As a [user type], I want to [action] so that [benefit]...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples
      placeholder: Paste images or links here...

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details or constraints to consider?
      placeholder: This might require changes to...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: Any other information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I am willing to help implement this feature
          required: false
