name: CI - Pull Request Validation

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [develop]

jobs:
  lint-and-format:
    name: Code Quality Checks
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

      - name: Check code formatting
        run: npm run format:check
        continue-on-error: false

      - name: TypeScript type checking
        run: npm run type-check
        continue-on-error: false

  security-audit:
    name: Security Audit
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: false

      - name: Check for known vulnerabilities
        run: npm audit --production --audit-level=high
        continue-on-error: false

      - name: Run Trivy security scan
        run: |
          trivy fs --severity HIGH,CRITICAL --exit-code 1 .
        continue-on-error: true

  build-test:
    name: Production Build Test
    runs-on: self-hosted
    needs: [lint-and-format]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build
        env:
          NODE_ENV: production

      - name: Check build output
        run: |
          if [ ! -d ".next" ]; then
            echo "Build output directory not found"
            exit 1
          fi
          echo "Build completed successfully"

  bundle-analysis:
    name: Bundle Size Analysis
    runs-on: self-hosted
    needs: [build-test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build for analysis
        run: npm run build
        env:
          NODE_ENV: production
          ANALYZE: true

      - name: Analyze bundle size
        run: |
          echo "Bundle Analysis Report"
          echo "======================"
          du -sh .next/static
          echo ""
          echo "Largest chunks:"
          find .next/static -name "*.js" -type f -exec du -h {} + | sort -rh | head -10

      - name: Check bundle size limits
        run: |
          BUNDLE_SIZE=$(du -sb .next/static | cut -f1)
          MAX_SIZE=$((5 * 1024 * 1024))  # 5MB limit

          if [ $BUNDLE_SIZE -gt $MAX_SIZE ]; then
            echo "Warning: Bundle size ($BUNDLE_SIZE bytes) exceeds recommended limit ($MAX_SIZE bytes)"
            echo "Consider code splitting or lazy loading to reduce bundle size"
          else
            echo "Bundle size is within acceptable limits: $BUNDLE_SIZE bytes"
          fi

  summary:
    name: CI Summary
    runs-on: self-hosted
    needs: [lint-and-format, security-audit, build-test, bundle-analysis]
    if: always()

    steps:
      - name: Check results
        run: |
          if [ "${{ needs.lint-and-format.result }}" != "success" ] || \
             [ "${{ needs.security-audit.result }}" != "success" ] || \
             [ "${{ needs.build-test.result }}" != "success" ] || \
             [ "${{ needs.bundle-analysis.result }}" != "success" ]; then
            echo "CI checks failed"
            exit 1
          fi
          echo "All CI checks passed successfully"
